// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://warrbhplolyvpipzqfam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhcnJiaHBsb2x5dnBpcHpxZmFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NTA1MDQsImV4cCI6MjA2MjEyNjUwNH0.hD9EnE5dBx5xPXDnCv0aeaiUSnvgHL_6ixEow08C7_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);